ALTER TABLE orders ADD COLUMN customerInstagram TEXT;
ALTER TABLE orders ADD COLUMN notes TEXT;
ALTER TABLE orders ADD COLUMN pickup INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN total INTEGER DEFAULT 0;
